      // ─── DATA ─────────────────────────────────────────────────────────────────────
      const CATS = [
        { id: 'about-me', label: 'About Me', emoji: '👤' },
        { id: 'family', label: 'Family', emoji: '👨‍👩‍👧' },
        { id: 'work', label: 'Work', emoji: '💼' },
        { id: 'school', label: 'School', emoji: '📖' },
        { id: 'health', label: 'Health', emoji: '💪' },
        { id: 'daily', label: 'Daily Life', emoji: '🌅' },
        { id: 'hobbies', label: 'Hobbies', emoji: '🎨' },
        { id: 'travel', label: 'Travel', emoji: '✈️' },
        { id: 'food', label: 'Food', emoji: '🍽️' },
        { id: 'society', label: 'Society', emoji: '🏙️' },
        { id: 'friends', label: 'Friends', emoji: '🤝' },
        { id: 'situations', label: 'Situations', emoji: '💡' },
        { id: 'opinions', label: 'Opinions', emoji: '💭' },
      ];

      const BASE_QS = [
        {
          id: 1,
          cat: 'about-me',
          examType: 'A',
          q: 'Kan du fortelle litt om deg selv?',
          a: 'Jeg heter [Navn] og er [Alder] år gammel. Jeg kommer fra [Land], men jeg har bodd i Norge i [Antall] år nå. Jeg jobber som [Yrke] og trives godt med det. Jeg går på skolen. Jeg er gift og har [1/2/3/4] barn. Eller jeg er ugift og bor alene / sammen med venner/familie. På fritiden liker jeg å [Hobby] og [Hobby]. Jeg lærer norsk fordi jeg ønsker å integrere meg bedre i det norske samfunnet. Jeg bor i en leilighet/hus, osv.',
        },
        {
          id: 2,
          cat: 'about-me',
          examType: 'A',
          q: 'Hvorfor lærer du norsk?',
          a: 'Jeg lærer norsk fordi jeg bor i Norge, og jeg vil snakke med folk. Det er viktig å forstå hva folk sier, for eksempel på jobb eller i butikken. Jeg trenger også norsk for å finne en bedre jobb. Så jeg prøver å øve hver dag – jeg leser, lytter og snakker med andre. Det er litt vanskelig, men det går bedre og bedre!',
        },
        {
          id: 3,
          cat: 'about-me',
          examType: 'A',
          q: 'Hva liker du best med Norge?',
          a: 'Jeg liker naturen best! Det er så fint med fjorder, fjell og skog. Om sommeren kan man gå tur og bade, og om vinteren kan man stå på ski. Jeg liker også at Norge er et trygt land. Folk er hyggelige, og det er lett å trives her.',
        },
        {
          id: 4,
          cat: 'about-me',
          examType: 'A',
          q: 'Hva er den største forskjellen mellom Norge og ditt hjemland?',
          a: 'Den største forskjellen er været! I Norge er det kaldt om vinteren, og det er mørkt store deler av dagen. I mitt hjemland er det mye varmere, og vi har sol nesten hele året. En annen forskjell er at folk i Norge er mer vant til å planlegge ting på forhånd. I mitt hjemland er vi mer spontane.',
        },
        {
          id: 5,
          cat: 'about-me',
          examType: 'A',
          q: 'Hva savner du mest fra ditt hjemland?',
          a: 'Jeg savner familien min mest! Det er ikke så lett å bo langt unna dem. Jeg savner også maten, fordi vi har mange spesielle retter som jeg ikke finner her. Været er også annerledes – hjemme er det varmere og mer sol. Men heldigvis kan jeg reise på besøk av og til.',
        },
        {
          id: 6,
          cat: 'about-me',
          examType: 'A',
          q: 'Hva er dine styrker og svakheter?',
          a: 'Jeg synes sosiale medier er både bra og dårlig. Det er fint fordi man kan holde kontakt med familie og venner, spesielt hvis de bor langt unna. Man kan også lære mye nytt og følge med på nyheter. Men det verste er TikTok og Instagram, hvor folk, spesielt ungdommer, bruker masse tid på ting som ikke er nyttige. Mange blir avhengige og glemmer viktige ting i livet. Jeg tror det er viktig å ha en balanse og ikke bruke for mye tid på mobilen.',
        },
        {
          id: 7,
          cat: 'about-me',
          examType: 'A',
          q: 'Hva er drømmene dine for fremtiden?',
          a: 'Drømmejobben min er å jobbe med språk og hjelpe folk som vil lære norsk. Jeg har hjulpet mange med å lære norsk, og jeg prøver alltid å finne nye måter som gjør språklæring rask og enkel. Jeg vil at folk skal lære uten at det koster dem masse penger eller tar lang tid. For meg er språk viktig, fordi det gir folk muligheter og gjør livet lettere. Det gjør meg glad å se at det jeg gjør, hjelper andre.',
        },
        {
          id: 8,
          cat: 'about-me',
          examType: 'A',
          q: 'Hva er du stolt av i livet ditt?',
          a: 'Jeg savner familien min mest! Det er ikke så lett å bo langt unna dem. Jeg savner også maten, fordi vi har mange spesielle retter som jeg ikke finner her. Været er også annerledes – hjemme er det varmere og mer sol. Men heldigvis kan jeg reise på besøk av og til.',
        },
        {
          id: 9,
          cat: 'family',
          examType: 'A',
          q: 'Kan du fortelle om familien din?',
          a: 'Klassen min er hyggelig. Vi er fra forskjellige land. Noen er fra Ukraina, og noen er fra Syria. Det er både menn og kvinner i klassen, men de fleste er kvinner. Noen har bodd lenge i Norge, og noen har kommet nylig. Vi lærer norsk sammen. Vi hjelper hverandre og snakker i pausene. Læreren er snill og forklarer bra. Jeg liker klassen fordi jeg lærer mye og får nye venner.',
        },
        {
          id: 10,
          cat: 'family',
          examType: 'A',
          q: 'Hva gjør familien din i helgene?',
          a: 'I helgen liker jeg å slappe av. Noen ganger sover jeg litt lenger. Jeg spiser en god frokost og drikker kaffe. Ofte går jeg en tur eller møter venner. Noen ganger besøker jeg familie. Hvis jeg har tid, ser jeg på YouTube eller en film. Jeg prøver også å gjøre litt husarbeid, for eksempel vaske klær eller rydde hjemme.',
        },
        {
          id: 11,
          cat: 'family',
          examType: 'B',
          q: 'Hva liker barn å gjøre og hva liker voksne å gjøre? Hva kan de gjøre sammen?',
          a: 'Barn liker å leke og være aktive. De liker å spille spill, tegne og se på tegnefilmer. Voksne liker ofte å slappe av, se på TV eller drikke kaffe og snakke sammen. Men barn og voksne kan også gjøre ting sammen. De kan gå på tur, lage mat eller spille spill. Det er fint å gjøre noe sammen som begge liker.',
        },
        {
          id: 12,
          cat: 'family',
          examType: 'A',
          q: 'Hva kan barn bestemme selv?',
          a: 'Barn kan bestemme noen ting selv, men ikke alt. De kan velge hvilken sport de vil spille og hva de vil spise fra det foreldrene lager. Men for eksempel kan de ikke bestemme å spise is i stedet for middag. De må også ha på seg jakke når det er kaldt. Foreldrene bestemmer fordi de vet hva som er best. Barn kan velge venner, men foreldrene må passe på at de er gode venner. De kan heller ikke gå ut og inn når de vil. Hjemme må det være regler for alle.',
        },
        {
          id: 13,
          cat: 'family',
          examType: 'C',
          q: 'Synes du det er viktig å bo nær familien sin?',
          a: 'Ja, jeg synes det er viktig å spise sunn mat. Sunn mat gir oss energi og gjør oss sterke. Jeg prøver å spise mye grønnsaker, frukt og proteiner som kjøtt eller fisk. Jeg prøver også å drikke nok vann og ikke spise for mye sukker. Hvis man spiser sunn mat, føler man seg bedre og har mer energi i hverdagen.',
        },
        {
          id: 14,
          cat: 'family',
          examType: 'C',
          q: 'Hva er fordelene og ulempene med å ha en stor familie?',
          a: 'Jeg har lyst til å reise til Spania. Der er det varmt og fint. Jeg liker sol og strand. Jeg vil også smake på spansk mat. Paella og tapas ser veldig godt ut. Kanskje jeg kan lære litt spansk også. Jeg håper jeg kan reise dit en dag.',
        },
        {
          id: 15,
          cat: 'family',
          examType: 'A',
          q: 'Hva betyr familie for deg?',
          a: 'Det viktigste for meg er å like jobben og ha hyggelige kollegaer. Jeg vil også lære noe nytt og utvikle meg. Det er en fordel hvis jobben er godt betalt og ikke for langt unna der jeg bor. Jeg liker å ha klare arbeidsoppgaver og føle at jeg gjør en god jobb. Når disse tingene er på plass, trives jeg på jobben.',
        },
        {
          id: 16,
          cat: 'family',
          examType: 'C',
          q: 'Bør begge foreldre jobbe fulltid, eller bør én være hjemme med barna?',
          a: 'Jeg synes det er viktig at begge foreldre har muligheten til å jobbe, men barna trenger også mye omsorg. I Norge er det bra at man kan jobbe deltid eller dele permisjonen mellom foreldrene. Jeg tror det viktigste er at barna har det bra og at foreldrene finner en løsning som passer for familien. Det finnes ikke ett riktig svar – det avhenger av familiens situasjon.',
        },
        {
          id: 83,
          cat: 'family',
          examType: 'A',
          q: 'Kan du fortelle om en typisk familie i hjemlandet ditt?',
          a: 'I mitt hjemland bor mange familier sammen. Ofte bor foreldre og barn i samme hus. Noen ganger bor også besteforeldre sammen med familien. Det er vanlig at mor og far jobber, og barna går på skole. Familien spiser middag sammen og hjelper hverandre i hverdagen. Familie er veldig viktig i min kultur.',
        },
        {
          id: 84,
          cat: 'family',
          examType: 'A',
          q: 'Kan du fortelle om en høytid du liker? Når på året er den? Hvilken mat spiser dere?',
          a: 'Jeg liker jul. Jul feires i desember, og mange i Norge feiler den sammen med familie. Folk pynter huset og tenner lys. På julaften spiser man god mat, for eksempel ribbe, pinnekjøtt eller kalkun. Mange gir gaver til hverandre. Det er en koselig tid med familie, mat og glede. Jeg liker Eid. Det er en av de viktigste høytidene for muslimer. Vi feirer den etter Ramadan. På morgenen går vi i moskeen og ber. Etterpå besøker vi familie og venner. Vi spiser mye god mat, for eksempel kjøttretter, ris og søtsaker. Barna får ofte gaver eller penger. Det er en dag med glede og feiring. o',
        },
        {
          id: 17,
          cat: 'work',
          examType: 'A',
          q: 'Hva jobber/studerer du med?',
          a: 'Jeg jobber som (yrke), og jeg trives godt. Jeg jobber vanligvis fra mandag til fredag, og arbeidsdagen min er ganske variert. Jeg liker jobben fordi den er interessant og gir meg nye utfordringer. Noen dager er travle, men det er også spennende. Jeg lærer noe nytt hele tiden! Akkurat nå går jeg på norskkurs fordi jeg vil bli bedre i språket. Jeg prøver å øve mye, både på skolen og hjemme. Når jeg blir flinkere i norsk, håper jeg å finne en jobb. Jeg er interessert i (yrke/bransje) og vil gjerne jobbe med det i fremtiden. Det er viktig for meg å lære norsk for å få flere muligheter.',
        },
        {
          id: 18,
          cat: 'work',
          examType: 'A',
          q: 'Kan du beskrive en typisk arbeidsdag?',
          a: 'I mitt hjemland bor mange familier sammen. Ofte bor foreldre og barn i samme hus. Noen ganger bor også besteforeldre sammen med familien. Det er vanlig at mor og far jobber, og barna går på skole. Familien spiser middag sammen og hjelper hverandre i hverdagen. Familie er veldig viktig i min kultur.',
        },
        {
          id: 19,
          cat: 'work',
          examType: 'A',
          q: 'Hva er viktig for deg i en jobb?',
          a: 'Det viktigste for meg er å like jobben og ha hyggelige kollegaer. Jeg vil også lære noe nytt og utvikle meg. Det er en fordel hvis jobben er godt betalt og ikke for langt unna der jeg bor. Jeg liker å ha klare arbeidsoppgaver og føle at jeg gjør en god jobb. Når disse tingene er på plass, trives jeg på jobben.',
        },
        {
          id: 20,
          cat: 'work',
          examType: 'C',
          q: 'Er det viktig å ha en jobb man liker?',
          a: 'Det viktigste for meg er å like jobben og ha hyggelige kollegaer. Jeg vil også lære noe nytt og utvikle meg. Det er en fordel hvis jobben er godt betalt og ikke for langt unna der jeg bor. Jeg liker å ha klare arbeidsoppgaver og føle at jeg gjør en god jobb. Når disse tingene er på plass, trives jeg på jobben.',
        },
        {
          id: 21,
          cat: 'work',
          examType: 'C',
          q: 'Hva er utfordringene ved å jobbe i Norge som innvandrer?',
          a: 'Jeg synes det er bra at Norge hjelper flyktninger som trenger beskyttelse. Mange kommer fra krig og vanskelige situasjoner, og de trenger et trygt sted å bo. Samtidig kan det være utfordrende å tilpasse seg et nytt land med et nytt språk. Jeg tror det er viktig at innvandrere lærer norsk og blir en del av samfunnet. Hvis alle bidrar og respekterer hverandre, blir det bedre for både nordmenn og innvandrere.',
        },
        {
          id: 22,
          cat: 'work',
          examType: 'A',
          q: 'Hva er drømmejobben din?',
          a: 'Drømmejobben min er å jobbe med språk og hjelpe folk som vil lære norsk. Jeg har hjulpet mange med å lære norsk, og jeg prøver alltid å finne nye måter som gjør språklæring rask og enkel. Jeg vil at folk skal lære uten at det koster dem masse penger eller tar lang tid. For meg er språk viktig, fordi det gir folk muligheter og gjør livet lettere. Det gjør meg glad å se at det jeg gjør, hjelper andre.',
        },
        {
          id: 23,
          cat: 'work',
          examType: 'C',
          q: 'Hva er positivt og negativt med å jobbe hjemmefra?',
          a: 'Det viktigste for meg er å like jobben og ha hyggelige kollegaer. Jeg vil også lære noe nytt og utvikle meg. Det er en fordel hvis jobben er godt betalt og ikke for langt unna der jeg bor. Jeg liker å ha klare arbeidsoppgaver og føle at jeg gjør en god jobb. Når disse tingene er på plass, trives jeg på jobben.',
        },
        {
          id: 24,
          cat: 'work',
          examType: 'A',
          q: 'Hvilke planer har du for framtida når det gjelder jobb/studier?',
          a: 'Jeg vil fortsette å jobbe i denne bransjen, men jeg håper å utvikle meg videre. Kanskje jeg kan ta et kurs eller en utdanning for å få mer kunnskap. Jeg liker jobben min, men i fremtiden vil jeg kanskje ha mer ansvar. Det er viktig for meg å lære nye ting og bli bedre i det jeg gjør. Jeg håper også å få en jobb med gode muligheter for å vokse. Først vil jeg bli flinkere i norsk, slik at jeg kan finne en jobb. Jeg håper å jobbe innen (yrke/bransje) fordi det interesserer meg. Kanskje jeg tar en utdanning eller et kurs for å få flere muligheter. Jeg vil gjerne ha en trygg og stabil jobb i fremtiden. Det viktigste for meg er å finne en jobb jeg trives med.',
        },
        {
          id: 45,
          cat: 'work',
          examType: 'A',
          q: 'Hvilke jobber har du erfaring fra?',
          a: 'Jeg har erfaring fra restaurant. Jeg har jobbet der i tre år. Jobben var spennende, og jeg lærte mye. Jeg jobbet med å lage mat og servere kunder. Jeg liker å jobbe i restaurant fordi jeg møter mange mennesker. Det er fint å jobbe i et team og få venner fra jobb.',
        },
        {
          id: 25,
          cat: 'school',
          examType: 'A',
          q: 'Har du tatt noe utdanning i Norge?',
          a: 'Jeg synes integrering er veldig viktig for å kunne leve et godt liv i Norge. Det handler om å lære språket, forstå kulturen og delta i samfunnet. Det er viktig å respektere norske verdier og tradisjoner. Men jeg mener også at det norske samfunnet må være åpent og inkluderende. Integrering er en toveisprosess.',
        },
        {
          id: 26,
          cat: 'school',
          examType: 'A',
          q: 'Hva gjør du for å lære norsk utenom norskkurset?',
          a: 'Jeg prøver å øve på norsk hver dag. Jeg ser på norske filmer og hører på podkaster for å bli vant til språket. Jeg snakker også med venner og kollegaer på norsk, selv om det noen ganger er vanskelig. Noen ganger leser jeg bøker eller aviser for å lære nye ord. Jeg tror det viktigste er å bruke språket så mye som mulig.',
        },
        {
          id: 27,
          cat: 'school',
          examType: 'A',
          q: 'Synes du det er lett eller vanskelig å lære norsk?',
          a: 'Ja, jeg synes det er viktig å spise sunn mat. Sunn mat gir oss energi og gjør oss sterke. Jeg prøver å spise mye grønnsaker, frukt og proteiner som kjøtt eller fisk. Jeg prøver også å drikke nok vann og ikke spise for mye sukker. Hvis man spiser sunn mat, føler man seg bedre og har mer energi i hverdagen.',
        },
        {
          id: 28,
          cat: 'school',
          examType: 'A',
          q: 'Hvordan lærer du norsk? Har du noen gode tips?',
          a: 'Jeg lærer norsk ved å snakke med folk. Jeg går på språkkafé og øver der. Det hjelper mye. Jeg snakker også med venner og andre studenter. Jeg ser også på videoer på YouTube med tekst. Det gjør det lettere å forstå språket. Et godt tips er å se på videoer og bruke norsk hver dag, selv om det er vanskelig.',
        },
        {
          id: 29,
          cat: 'school',
          examType: 'C',
          q: 'Er utdanning viktig for å lykkes i livet?',
          a: 'Trening er viktig for helsen fordi det gir oss mer energi og gjør kroppen sterkere. Hvis man trener regelmessig, blir man sunnere og føler seg bedre. Trening hjelper også mot stress og gjør at man sover bedre. Man trenger ikke å trene hardt, men det er bra å gå tur, sykle eller gjøre enkle øvelser hver dag.',
        },
        {
          id: 30,
          cat: 'school',
          examType: 'A',
          q: 'Kan du fortelle om en vanlig skoledag?',
          a: 'Vi begynner på skolen klokka kvart over åtte. Først har vi undervisning. Noen ganger leser vi tekster, og noen ganger øver vi på å snakke norsk. Vi tar lunsjpause fra halv tolv til tolv. Etter pausen fortsetter vi med undervisning. Noen ganger jobber vi alene, og noen ganger jobber vi i grupper. Vi er ferdige klokka 15. Når skoledagen er ferdig, går jeg hjem og gjør lekser eller ser på videoer på YouTube for å lære mer.',
        },
        {
          id: 31,
          cat: 'school',
          examType: 'A',
          q: 'Hva gjør du i pausene når du er på skolen?',
          a: 'I pausene slapper jeg av. Jeg spiser mat og drikker kaffe eller te. Noen ganger snakker jeg med venner og klassekamerater. Hvis det er fint vær, går vi en liten tur ute. Noen ganger bruker jeg mobilen til å sjekke nyheter eller sende meldinger. Pausen er bra for å hvile før vi fortsetter undervisningen.',
        },
        {
          id: 32,
          cat: 'school',
          examType: 'A',
          q: 'Kan du fortelle om klassen din?',
          a: 'Klassen min er hyggelig. Vi er fra forskjellige land. Noen er fra Ukraina, og noen er fra Syria. Det er både menn og kvinner i klassen, men de fleste er kvinner. Noen har bodd lenge i Norge, og noen har kommet nylig. Vi lærer norsk sammen. Vi hjelper hverandre og snakker i pausene. Læreren er snill og forklarer bra. Jeg liker klassen fordi jeg lærer mye og får nye venner.',
        },
        {
          id: 33,
          cat: 'school',
          examType: 'A',
          q: 'Hva liker du å gjøre på norskkurs?',
          a: 'På norskkurset liker jeg å snakke norsk. Det hjelper meg å bli bedre. Jeg liker også å lese tekster og lære nye ord. Noen ganger jobber vi i grupper, og det er fint å snakke med andre. Jeg liker også når vi ser på videoer og diskuterer dem. Det er en god måte å lære norsk på.',
        },
        {
          id: 34,
          cat: 'school',
          examType: 'A',
          q: 'Liker du å jobbe alene eller sammen med andre på norskkurs?',
          a: 'Jeg liker å jobbe sammen med andre. Da kan vi snakke norsk og hjelpe hverandre. Det er lettere å lære når vi øver sammen. Men når jeg skriver en tekst eller jobber med grammatikk, liker jeg å jobbe alene. Da kan jeg tenke mer og jobbe i mitt eget tempo.',
        },
        {
          id: 35,
          cat: 'school',
          examType: 'A',
          q: 'Hvilke typer oppgaver liker du best å jobbe med?',
          a: 'Jeg liker best å jobbe med muntlige oppgaver. Det hjelper meg å snakke bedre norsk. Jeg liker også å lese tekster og lære nye ord. Noen ganger liker jeg å skrive, men det kan være vanskelig. Grammatikkoppgaver er viktige, men de er ikke alltid lett å forstå.',
        },
        {
          id: 36,
          cat: 'health',
          examType: 'A',
          q: 'Hva gjør du for å holde deg i form?',
          a: 'Jeg prøver å trene regelmessig for å holde meg i form. Jeg går på treningsstudio to-tre ganger i uken og løfter vekter. Jeg liker også å gå turer i naturen og sykle. Jeg prøver å spise sunt og unngå for mye sukker og fett. Jeg føler meg mye bedre når jeg er i god form.',
        },
        {
          id: 37,
          cat: 'health',
          examType: 'A',
          q: 'Hva gjør du for å ta vare på helsen din?',
          a: 'For å ta vare på helsen min prøver jeg å gå tur hver dag. Noen ganger trener jeg litt hjemme eller ute. Jeg passer også på å spise sunn mat og drikke mye vann. Jeg prøver å sove godt, fordi søvn er viktig for kroppen. Alt dette hjelper meg å ha mer energi og føle meg bra.',
        },
        {
          id: 38,
          cat: 'health',
          examType: 'C',
          q: 'Synes du helsevesenet i Norge er bra?',
          a: 'Jeg synes helsevesenet i Norge er bra fordi man får god behandling, og det er gratis på sykehuset. Men det tar ofte lang tid å få time hos legen eller på sykehuset. Noen må vente flere måneder på en operasjon, og det kan være frustrerende. Samtidig er det bra at alle har rett til helsehjelp uansett økonomi. Selv om ventetiden er lang, føler jeg meg trygg på at jeg får god hjelp når jeg trenger det..',
        },
        {
          id: 39,
          cat: 'health',
          examType: 'A',
          q: 'Hva er viktigst for å leve et sunt liv?',
          a: 'Det viktigste for meg er å like jobben og ha hyggelige kollegaer. Jeg vil også lære noe nytt og utvikle meg. Det er en fordel hvis jobben er godt betalt og ikke for langt unna der jeg bor. Jeg liker å ha klare arbeidsoppgaver og føle at jeg gjør en god jobb. Når disse tingene er på plass, trives jeg på jobben.',
        },
        {
          id: 40,
          cat: 'health',
          examType: 'A',
          q: 'Hva gjør du når du er syk?',
          a: 'Når jeg er syk prøver jeg å ta det med ro og hvile. Jeg drikker mye vann og spiser sunn mat. Hvis jeg har feber eller smerter tar jeg smertestillende. Hvis jeg ikke blir bedre etter noen dager kontakter jeg legen. Jeg prøver å unngå å smitte andre.',
        },
        {
          id: 41,
          cat: 'health',
          examType: 'C',
          q: 'Hva synes du om røyking?',
          a: 'Jeg synes røyking er veldig skadelig for helsa. Det kan gi mange sykdommer, for eksempel lungekreft og hjerteproblemer. I tillegg er det veldig dyrt å røyke i Norge, fordi tobakk koster mye. Jeg kjenner noen som røyker, og de sier at det er vanskelig å slutte. Jeg tror det er best å unngå røyking, både for helsa og økonomien.',
        },
        {
          id: 42,
          cat: 'health',
          examType: 'C',
          q: 'Synes du det er bra at folk er opptatt av kropp og helse?',
          a: 'Ja, jeg synes det er bra at folk er opptatt av helse, fordi det fører til et bedre og lengre liv. Det er viktig å trene og spise sunt. Men jeg synes man skal passe på at det ikke blir for mye fokus på utseende. Det viktigste er å ha det bra, ikke å se perfekt ut. En sunn balanse er det beste.',
        },
        {
          id: 43,
          cat: 'health',
          examType: 'C',
          q: 'Bør folk ta mer ansvar for sin egen helse?',
          a: 'Ja, jeg mener at folk bør ta mer ansvar for sin egen helse. Vi vet at røyking, dårlig mat og lite mosjon er skadelig. Staten kan ikke gjøre alt – hver enkelt av oss har et ansvar. Men samfunnet bør også gjøre det lettere å leve sunt, for eksempel med billigere sunn mat og gode treningsanlegg.',
        },
        {
          id: 44,
          cat: 'daily',
          examType: 'A',
          q: 'Hva gjør du en vanlig dag?',
          a: 'En vanlig dag står jeg opp tidlig. Først spiser jeg frokost og drikker kaffe. Så gjør jeg meg klar og går ut. Hvis jeg har jobb eller skole, drar jeg dit. Etterpå handler jeg mat eller går en tur. Om kvelden lager jeg middag og slapper av. Noen ganger ser jeg på YouTube eller snakker med familie. Jeg legger meg ikke for sent, så jeg er klar for neste dag.',
        },
        {
          id: 46,
          cat: 'daily',
          examType: 'A',
          q: 'Hvordan kommer du deg til jobb?',
          a: 'Jeg tar buss til norskkurset. Det tar cirka 30 minutter. Noen ganger må jeg vente på bussen, spesielt om vinteren. Hvis været er fint, liker jeg å gå litt også. Det er fint å ha litt tid på bussen til å høre på musikk eller se på YouTube.',
        },
        {
          id: 47,
          cat: 'daily',
          examType: 'A',
          q: 'Hva spiser du til frokost, lunsj og middag?',
          a: 'Jeg savner familien min mest! Det er ikke så lett å bo langt unna dem. Jeg savner også maten, fordi vi har mange spesielle retter som jeg ikke finner her. Været er også annerledes – hjemme er det varmere og mer sol. Men heldigvis kan jeg reise på besøk av og til.',
        },
        {
          id: 48,
          cat: 'daily',
          examType: 'A',
          q: 'Hva gjør du i helgene?',
          a: 'I helgen liker jeg å slappe av. Noen ganger sover jeg litt lenger. Jeg spiser en god frokost og drikker kaffe. Ofte går jeg en tur eller møter venner. Noen ganger besøker jeg familie. Hvis jeg har tid, ser jeg på YouTube eller en film. Jeg prøver også å gjøre litt husarbeid, for eksempel vaske klær eller rydde hjemme.',
        },
        {
          id: 49,
          cat: 'daily',
          examType: 'C',
          q: 'Er det viktig å ha rutiner i hverdagen?',
          a: 'Jeg synes internett er den viktigste oppfinnelsen. Vi bruker det til nesten alt – jobbing, læring og kontakt med andre. Uten internett hadde det vært vanskelig å finne informasjon og holde kontakt med familien. Det gjør livet lettere og mer spennende. Jeg kan ikke forestille meg en verden uten internett.',
        },
        {
          id: 50,
          cat: 'daily',
          examType: 'A',
          q: 'Hva bruker du penger på hver måned?',
          a: 'Hver måned bruker jeg penger på husleie, mat og strøm. Jeg må også betale for buss eller bil. Noen ganger kjøper jeg klær eller andre ting jeg trenger. Hvis jeg har ekstra penger, sparer jeg litt eller bruker dem på noe hyggelig med familien.',
        },
        {
          id: 51,
          cat: 'daily',
          examType: 'A',
          q: 'Hva sparer du penger til?',
          a: 'Jeg sparer penger til framtiden. Jeg vil ha penger hvis noe viktig skjer. Kanskje jeg vil kjøpe et hus eller en bil en dag. Jeg sparer også til ferie, så jeg kan reise og besøke familie. Det er fint å ha litt ekstra penger i tilfelle jeg trenger det.',
        },
        {
          id: 52,
          cat: 'daily',
          examType: 'A',
          q: 'Hva bruker du internett til?',
          a: 'Jeg bruker internett til mange ting. Jeg ser på YouTube og leser nyheter. Jeg bruker også internett for å lære norsk. Noen ganger snakker jeg med familie og venner på video. Jeg bruker også internett til å finne informasjon og handle på nett.',
        },
        {
          id: 53,
          cat: 'daily',
          examType: 'A',
          q: 'Hvordan holder du kontakt med venner og familie som bor andre steder?',
          a: 'Jeg holder kontakt med venner og familie på telefon. Vi sender meldinger og ringer hverandre. Noen ganger bruker vi videosamtale, for eksempel på WhatsApp eller Messenger. Hvis vi har tid og penger, prøver vi å besøke hverandre. Det er viktig for meg å holde kontakt med dem.',
        },
        {
          id: 54,
          cat: 'daily',
          examType: 'A',
          q: 'Kan du fortelle om hva som gjør deg glad i hverdagen?',
          a: 'Mange små ting gjør meg glad i hverdagen. Jeg blir glad når jeg lærer noe nytt eller får til noe vanskelig. Jeg liker også å snakke med familie og venner. En hyggelig melding eller et smil fra noen kan gjøre dagen min bedre. Jeg blir også glad når været er fint, eller når jeg drikker en god kopp kaffe eller te. Små ting betyr mye.',
        },
        {
          id: 55,
          cat: 'daily',
          examType: 'A',
          q: 'Hvordan bor du? I en enebolig, en leilighet eller et rekkehus?',
          a: 'Jeg bor i en leilighet. Den er ikke så stor, men det er nok plass for meg. Jeg har et soverom, en stue, et kjøkken og et bad. Jeg liker leiligheten fordi den er koselig. Det er også kort vei til butikk og buss. Jeg trives godt her.',
        },
        {
          id: 56,
          cat: 'daily',
          examType: 'A',
          q: 'Hvilket rom liker du best i huset ditt?',
          a: 'Jeg liker stua best i huset mitt. Der kan jeg slappe av og se på TV . Stua har en sofa, et bord og en TV . Jeg liker også kjøkkenet fordi jeg liker å lage mat. På kjøkkenet har jeg et spisebord, stoler og skap med kjøkkenutstyr. Jeg synes det er viktig å ha et koselig hjem.',
        },
        {
          id: 57,
          cat: 'daily',
          examType: 'A',
          q: 'Hvor kjøper du mat? Hvor ofte går du på butikken?',
          a: 'Jeg kjøper mat i matbutikken nær hjemmet mitt. Ofte handler jeg på Kiwi eller Rema 1000 fordi de har gode priser. Noen ganger går jeg til forskjellige butikker for å finne gode tilbud. Jeg handler mat cirka to til tre ganger i uka. Jeg liker å kjøpe frukt, grønnsaker, kjøtt og brød. Noen ganger kjøper jeg også noe godt, for eksempel sjokolade eller snacks.',
        },
        {
          id: 58,
          cat: 'hobbies',
          examType: 'A',
          q: 'Hva liker du å gjøre på fritiden?',
          a: 'På fritiden liker jeg å lese bøker og se filmer. Jeg er også glad i å gå turer i naturen, spesielt i helgene. Jeg prøver å trene regelmessig for å holde meg i form. I tillegg liker jeg å tilbringe tid med venner og familie. Det er viktig for meg å ha en balanse mellom aktivitet og avslapning.',
        },
        {
          id: 59,
          cat: 'hobbies',
          examType: 'A',
          q: 'Har du noen spesielle interesser eller hobbyer?',
          a: 'Ja, jeg liker å høre på musikk og lese bøker. Jeg liker også å gå tur i naturen, spesielt om sommeren. Noen ganger trener jeg på treningssenter eller svømmer. I helgene liker jeg å være med venner og familie. Det er viktig for meg å gjøre noe jeg liker på fritiden.',
        },
        {
          id: 60,
          cat: 'hobbies',
          examType: 'A',
          q: 'Hva er den viktigste oppfinnelsen i verden, synes du?',
          a: 'Jeg synes internett er den viktigste oppfinnelsen. Vi bruker det til nesten alt – jobbing, læring og kontakt med andre. Uten internett hadde det vært vanskelig å finne informasjon og holde kontakt med familien. Det gjør livet lettere og mer spennende. Jeg kan ikke forestille meg en verden uten internett.',
        },
        {
          id: 61,
          cat: 'hobbies',
          examType: 'A',
          q: 'Hva slags musikk liker du?',
          a: 'Jeg liker mange forskjellige typer musikk, men jeg er spesielt glad i jazz. Jeg synes jazzmusikere er utrolig dyktige og kreative. Det er noe spesielt med improvisasjonen og rytmene. Jeg går ofte på konserter for å høre live jazz. Det gir meg energi og inspirasjon.',
        },
        {
          id: 62,
          cat: 'hobbies',
          examType: 'A',
          q: 'Hvilken musikk liker du ikke?',
          a: 'Jeg liker ikke musikk som er veldig høy og bråkete. For eksempel heavy metal eller veldig rask techno. Jeg synes det er stressende å høre på. Jeg liker heller ikke musikk med stygge ord. Jeg foretrekker musikk som har en fin melodi og gode tekster.',
        },
        {
          id: 63,
          cat: 'hobbies',
          examType: 'A',
          q: 'Kan du fortelle om en film eller TV-serie du liker?',
          a: 'Jeg liker filmer og TV-serier som er spennende og interessante. Jeg liker serier med en god historie, og jeg liker også komedier fordi de er morsomme. Noen ganger ser jeg på filmer som handler om virkelige hendelser, fordi jeg liker å lære noe nytt. Jeg ser ofte filmer og serier på norsk for å øve på språket.',
        },
        {
          id: 64,
          cat: 'hobbies',
          examType: 'A',
          q: 'Ser du mer eller mindre på TV etter at du kom til Norge?',
          a: 'Etter at jeg kom til Norge, ser jeg mer på TV . Det er fordi livet her er litt roligere, og det er færre sosiale aktiviteter enn i hjemlandet mitt. Jeg ser ofte på nyheter, filmer og TV-serier. Jeg ser også mye på YouTube på TV , fordi det finnes mange videoer som hjelper meg å lære norsk.',
        },
        {
          id: 65,
          cat: 'hobbies',
          examType: 'C',
          q: 'Synes du det er viktig å ha hobbyer?',
          a: 'Ja, jeg synes det er viktig å spise sunn mat. Sunn mat gir oss energi og gjør oss sterke. Jeg prøver å spise mye grønnsaker, frukt og proteiner som kjøtt eller fisk. Jeg prøver også å drikke nok vann og ikke spise for mye sukker. Hvis man spiser sunn mat, føler man seg bedre og har mer energi i hverdagen.',
        },
        {
          id: 66,
          cat: 'hobbies',
          examType: 'A',
          q: 'Kan du fortelle om noe du er flink til?',
          a: 'Jeg er flink til å lage mat. Jeg liker å prøve nye oppskrifter og lage god mat til familie og venner. Jeg har lært å lage mat fra moren min og fra videoer på YouTube. Jeg liker spesielt å lage retter med kjøtt, ris og grønnsaker. Det gjør meg glad når folk liker maten min.',
        },
        {
          id: 67,
          cat: 'hobbies',
          examType: 'A',
          q: 'Hva er du ikke flink til?',
          a: 'Jeg er ikke flink til å danse. Jeg liker musikk, men jeg føler meg litt ukomfortabel når jeg skal danse. Jeg prøver noen ganger, men det er ikke lett for meg. Kanskje jeg kan bli bedre hvis jeg øver mer.',
        },
        {
          id: 68,
          cat: 'hobbies',
          examType: 'A',
          q: 'Kan du fortelle om noe du vil lære?',
          a: 'Jeg vil ikke jobbe som fisker. Det er en viktig jobb, men det er hardt arbeid. Man må jobbe lange dager, ofte ute i kaldt vær. Jeg liker bedre en jobb der jeg kan være inne og jobbe med mennesker. Men jeg respekterer de som jobber med det, fordi det er viktig for samfunnet.',
        },
        {
          id: 69,
          cat: 'travel',
          examType: 'A',
          q: 'Fortell om et sted i Norge du har vært eller ønsker å reise til.',
          a: 'Jeg har lyst til å reise til Spania. Der er det varmt og fint. Jeg liker sol og strand. Jeg vil også smake på spansk mat. Paella og tapas ser veldig godt ut. Kanskje jeg kan lære litt spansk også. Jeg håper jeg kan reise dit en dag.',
        },
        {
          id: 70,
          cat: 'travel',
          examType: 'A',
          q: 'Hvor vil du reise i fremtiden?',
          a: 'Jeg vil gjerne reise til Spania fordi det er mye sol der, noe vi ofte mangler i Norge! Jeg har hørt at Spania har vakre strender og deilig vær nesten hele året. Jeg vil besøke Barcelona. Jeg liker også spansk mat, spesielt paella og tapas. Det hadde vært fantastisk å slappe av på en strand og nyte solen.',
        },
        {
          id: 71,
          cat: 'travel',
          examType: 'A',
          q: 'Hva liker du å gjøre på ferie?',
          a: 'På ferie liker jeg å slappe av og utforske nye steder. Jeg liker å gå turer i naturen og besøke museer og historiske steder. Jeg er også glad i å prøve ny mat og lære om lokale kulturer. Det viktigste er å koble av fra hverdagen og nyte friheten.',
        },
        {
          id: 72,
          cat: 'travel',
          examType: 'A',
          q: 'Hva er din drømmeferie?',
          a: 'Min drømmeferie er en tur til et varmt og fint sted, for eksempel Maldivene eller Santorini. Jeg vil gjerne slappe av på stranden, bade i varmt vann og nyte solen. Det hadde vært deilig å bo på et fint hotell, spise god mat og kanskje gå på spa. Jeg liker også å oppleve nye steder, så jeg ville gått rundt i byen og sett på fine steder. En ferie med sol, ro og litt luksus hadde vært perfekt.',
        },
        {
          id: 73,
          cat: 'travel',
          examType: 'C',
          q: 'Hvorfor er det viktig å reise, synes du?',
          a: 'Jeg synes det er viktig å reise fordi man lærer mye om andre kulturer og perspektiver. Man får et bredere syn på verden og blir mer tolerant. Det er også en fin måte å slappe av og få nye opplevelser. Reise kan også utfordre deg til å tenke nytt om deg selv og ditt eget liv.',
        },
        {
          id: 74,
          cat: 'travel',
          examType: 'A',
          q: 'Hva liker du å gjøre om sommeren?',
          a: 'Om sommeren liker jeg å være ute. Hvis været er fint, går jeg tur eller drar til stranda. Jeg liker også å grille og spise ute med familie og venner. Noen ganger reiser jeg til andre byer eller land. Sommeren er en fin tid til å slappe av og nyte solen.',
        },
        {
          id: 75,
          cat: 'travel',
          examType: 'A',
          q: 'Hvordan er sommeren der du kommer fra?',
          a: 'Sommeren i mitt hjemland er varm. Temperaturen er ofte mellom 25 og 30 grader. Noen dager kan det være veldig varmt, og noen dager kan det regne litt. Mange drar til stranda, fjellene eller besøker familie på landet. Vi liker å være ute, grille og spise ferske frukter og grønnsaker. Sommeren er en fin tid for å gjøre mange oppgaver som man ikke kan gjøre om vinteren, for eksempel, å male huset, jobbe i hagen eller reise mer.',
        },
        {
          id: 76,
          cat: 'travel',
          examType: 'A',
          q: 'Hva synes du om vinteren i Norge?',
          a: 'Vinteren i Norge er kald og mørk. Noen ganger er det mye snø, og noen ganger regner det. Jeg synes vinteren kan være fin, spesielt når det er snø og sol. Men det kan også være vanskelig når det er veldig kaldt og glatt ute. Jeg liker å drikke varm te og være inne når det er for kaldt. Noen ganger går jeg på tur eller ser på snøen fra vinduet.',
        },
        {
          id: 77,
          cat: 'travel',
          examType: 'A',
          q: 'Hva liker du å gjøre om vinteren?',
          a: 'Om vinteren liker jeg å være inne når det er veldig kaldt. Jeg drikker varm te eller kakao og ser på filmer. Noen ganger går jeg en tur hvis det ikke er for kaldt. Hvis det er snø, liker jeg å leke ute eller gå på ski. Jeg prøver også å være sosial og besøke venner eller familie.',
        },
        {
          id: 78,
          cat: 'travel',
          examType: 'A',
          q: 'Hva liker du å gjøre når det er fint vær?',
          a: 'Når det er fint vær, liker jeg å være ute. Jeg går ofte en tur eller sitter i parken. Noen ganger drar jeg til stranda eller griller med venner. Hvis jeg har tid, kan jeg også reise til et nytt sted og nyte naturen. Fint vær gjør meg glad, og jeg prøver å bruke dagen godt.',
        },
        {
          id: 79,
          cat: 'food',
          examType: 'A',
          q: 'Hva slags mat serverer du når du har besøk?',
          a: 'Når jeg har besøk, lager jeg alltid noe godt. I min kultur er det viktig å servere kjøtt eller kylling til gjester. Det viser respekt og gjestfrihet. Hvis det er et stort besøk eller en spesiell anledning, lager jeg en tradisjonell rett med kjøtt, ris eller brød. Hvis besøket er mer uformelt, for eksempel nære venner eller familie, kan jeg lage noe enklere, som pasta eller grønnsaker. Det viktigste for meg er at gjestene føler seg velkomne og trives.',
        },
        {
          id: 80,
          cat: 'food',
          examType: 'A',
          q: 'Hva synes du om norsk mat?',
          a: 'Jeg synes norsk mat er god, men den er litt annerledes enn maten fra hjemlandet mitt. Jeg liker fisk, poteter og kjøttkaker. Noen retter smaker litt mildt for meg, fordi jeg er vant til mer krydder. Men jeg liker å prøve nye ting. Jeg synes også norsk mat er sunn og enkel å lage.',
        },
        {
          id: 81,
          cat: 'food',
          examType: 'C',
          q: 'Synes du det er viktig å spise sunn mat?',
          a: 'Ja, jeg synes det er viktig å spise sunn mat. Sunn mat gir oss energi og gjør oss sterke. Jeg prøver å spise mye grønnsaker, frukt og proteiner som kjøtt eller fisk. Jeg prøver også å drikke nok vann og ikke spise for mye sukker. Hvis man spiser sunn mat, føler man seg bedre og har mer energi i hverdagen.',
        },
        {
          id: 82,
          cat: 'food',
          examType: 'A',
          q: 'Hva liker du å spise? Hva slags mat liker du best?',
          a: 'For meg er det aldri veldig varmt i Norge. Men når det er varme dager, liker jeg å være ute. Vi går på stranda eller på tur. Da spiser vi noe enkelt, for eksempel pølser eller annen lett mat. Når det er kaldt, liker jeg varm mat, for eksempel suppe eller gryterett. Det gjør meg varm og mett.',
        },
        {
          id: 85,
          cat: 'food',
          examType: 'A',
          q: 'Hva liker du å spise når det er kaldt/varmt ute?',
          a: 'For meg er det aldri veldig varmt i Norge. Men når det er varme dager, liker jeg å være ute. Vi går på stranda eller på tur. Da spiser vi noe enkelt, for eksempel pølser eller annen lett mat. Når det er kaldt, liker jeg varm mat, for eksempel suppe eller gryterett. Det gjør meg varm og mett.',
        },
        {
          id: 86,
          cat: 'food',
          examType: 'A',
          q: 'Kan du lage mat? Hva lager du best?',
          a: 'Jeg liker å spise variert mat, men jeg er spesielt glad i italiensk mat. Jeg elsker pizza og pasta og alt som er laget med tomater og olivenolje. Jeg prøver å lage mat hjemme så ofte som mulig. Da vet jeg hva jeg får i meg. Jeg er også åpen for å prøve nye retter fra forskjellige land.',
        },
        {
          id: 87,
          cat: 'food',
          examType: 'A',
          q: 'Hva liker du å drikke? Liker du best varm eller kald drikke?',
          a: 'Jeg liker både varm og kald drikke. Om morgenen liker jeg å drikke kaffe eller te. Når det er kaldt ute, drikker jeg ofte varm te eller mate. Når det er varmt, liker jeg å drikke kaldt vann eller juice. Det viktigste for meg er at drikken smaker godt.',
        },
        {
          id: 88,
          cat: 'food',
          examType: 'A',
          q: 'Kan du fortelle om en fest du har vært på?',
          a: 'Ja, jeg har vært på en bursdagsfest for en venn. Det var veldig hyggelig. Vi spiste god mat og kake. Det var musikk, og noen danset. Vi snakket og lo mye sammen. Jeg møtte også nye mennesker. Det var en fin kveld, og alle hadde det gøy.',
        },
        {
          id: 89,
          cat: 'society',
          examType: 'C',
          q: 'Hva er dine tanker om integrering i Norge?',
          a: 'Jeg synes integrering er veldig viktig for å kunne leve et godt liv i Norge. Det handler om å lære språket, forstå kulturen og delta i samfunnet. Det er viktig å respektere norske verdier og tradisjoner. Men jeg mener også at det norske samfunnet må være åpent og inkluderende. Integrering er en toveisprosess.',
        },
        {
          id: 90,
          cat: 'society',
          examType: 'C',
          q: 'Hva er dine tanker om innvandring?',
          a: 'Jeg synes det er bra at Norge hjelper flyktninger som trenger beskyttelse. Mange kommer fra krig og vanskelige situasjoner, og de trenger et trygt sted å bo. Samtidig kan det være utfordrende å tilpasse seg et nytt land med et nytt språk. Jeg tror det er viktig at innvandrere lærer norsk og blir en del av samfunnet. Hvis alle bidrar og respekterer hverandre, blir det bedre for både nordmenn og innvandrere.',
        },
        {
          id: 91,
          cat: 'society',
          examType: 'A',
          q: 'Hva er din favoritt norske tradisjon?',
          a: 'Jeg liker 17. mai best! Det er en dag med mye glede, fine klær og god mat. Jeg synes det er fint å se barnetoget og folk som feirer sammen. Mange spiser is og pølser, og det er en hyggelig stemning overalt. Jeg liker at hele landet feirer sammen, og at alle kan være med uansett hvor de kommer fra.',
        },
        {
          id: 92,
          cat: 'society',
          examType: 'C',
          q: 'Hva er dine tanker om likestilling mellom menn og kvinner?',
          a: 'Jeg synes likestilling er veldig viktig. Menn og kvinner bør ha de samme mulighetene, både på jobb og i familien. I Norge er det mange rettigheter for kvinner. Jeg mener at alle skal behandles rettferdig, uansett kjønn. Det viktigste er at både menn og kvinner har frihet til å velge hvordan de vil leve livet sitt.',
        },
        {
          id: 93,
          cat: 'society',
          examType: 'C',
          q: 'Hva synes du om det norske skolesystemet?',
          a: 'Jeg synes det norske skolesystemet er veldig bra. Alle har rett til gratis utdanning. Lærerne er flinke, og elevene lærer mye. Jeg synes det er viktig at skolen legger vekt på både faglig kunnskap og personlig utvikling. Jeg er imponert over at skolen tilpasser seg elevenes behov.',
        },
        {
          id: 94,
          cat: 'society',
          examType: 'C',
          q: 'Hva er dine tanker om klimaendringene?',
          a: 'Jeg synes klimaendringene er et stort problem. Vi ser allerede at været har forandret seg, med mer ekstremvær og varmere somre. Jeg tror vi må bli flinkere til å ta vare på naturen, for eksempel ved å bruke mindre plast og reise mer miljøvennlig. Store land og selskaper har også et ansvar for å redusere utslipp. Hvis alle gjør litt, kan vi kanskje bremse klimaendringene.',
        },
        {
          id: 95,
          cat: 'society',
          examType: 'C',
          q: 'Hva er dine tanker om krigen i Ukraina?',
          a: 'Jeg synes det er veldig trist at det er krig i Ukraina. Mange uskyldige mennesker mister hjemmene sine og må flykte. Det er vanskelig å forstå at det fortsatt er krig i verden i dag. Jeg håper at krigen snart tar slutt, og at folk kan leve trygt igjen. Ingen burde måtte oppleve noe sånt..',
        },
        {
          id: 96,
          cat: 'society',
          examType: 'C',
          q: 'Hva er dine tanker om økningen i strømpriser?',
          a: 'Jeg synes strømprisene har blitt altfor høye. Det er spesielt vanskelig for familier med lav inntekt. Mange må spare på strøm og bruke mindre varme om vinteren, og det er ikke bra. Jeg synes staten burde gjøre mer for å hjelpe folk, og strøm burde være gratis for alle familier. Strøm er noe alle trenger, og det burde ikke være så dyrt.',
        },
        {
          id: 97,
          cat: 'society',
          examType: 'C',
          q: 'Hva er dine tanker om kunstig intelligens?',
          a: 'Jeg synes kunstig intelligens er spennende, men litt skummelt også. Det kan gjøre livet lettere, for eksempel med roboter og smarte systemer som hjelper oss i hverdagen. Samtidig er jeg litt bekymret for at mange jobber kan forsvinne i fremtiden. Jeg tror vi må bruke kunstig intelligens på en smart måte, slik at det hjelper mennesker og ikke erstatter dem. Teknologi er bra, men vi må være forsiktige med hvordan vi bruker den.',
        },
        {
          id: 98,
          cat: 'society',
          examType: 'C',
          q: 'Hva er dine tanker om sosiale medier?',
          a: 'Jeg synes sosiale medier er både bra og dårlig. Det er fint fordi man kan holde kontakt med familie og venner, spesielt hvis de bor langt unna. Man kan også lære mye nytt og følge med på nyheter. Men det verste er TikTok og Instagram, hvor folk, spesielt ungdommer, bruker masse tid på ting som ikke er nyttige. Mange blir avhengige og glemmer viktige ting i livet. Jeg tror det er viktig å ha en balanse og ikke bruke for mye tid på mobilen.',
        },
        {
          id: 99,
          cat: 'society',
          examType: 'C',
          q: 'Hva gjør du for å ta vare på miljøet?',
          a: 'Jeg prøver å ta vare på miljøet hver dag. Jeg kaster søppel i riktig søppelbøtte og resirkulerer plast og papir. Jeg prøver også å bruke mindre strøm og vann. Hvis jeg kan, går jeg eller tar buss i stedet for bil. Jeg tar med meg handlenett når jeg handler, så jeg bruker mindre plast.',
        },
        {
          id: 100,
          cat: 'society',
          examType: 'C',
          q: 'Hva synes du bør være gratis i Norge?',
          a: 'Jeg synes at helsevesen og tannlege bør være gratis for alle. Det er viktig at alle får hjelp når de er syke, uten å tenke på penger. Jeg mener også at utdanning bør være gratis, slik at alle har mulighet til å lære og få en god jobb. Buss og tog burde også være billigere eller gratis, spesielt for studenter og eldre.',
        },
        {
          id: 101,
          cat: 'society',
          examType: 'C',
          q: 'Mener du at innvandrere bør tilpasse seg norsk kultur?',
          a: 'Jeg mener at alle foreldre bør lære barna å være snille og respektere andre. Det er viktig at barn lærer gode verdier, for eksempel å være ærlige og hjelpsomme. Foreldre bør også lære barna å ta ansvar, for eksempel å rydde etter seg og gjøre lekser. Det er også viktig å lære dem å være høflige og takke for hjelp.',
        },
        {
          id: 102,
          cat: 'society',
          examType: 'C',
          q: 'Hva mener du alle foreldre bør lære barna sine?',
          a: 'Jeg mener at alle foreldre bør lære barna å være snille og respektere andre. Det er viktig at barn lærer gode verdier, for eksempel å være ærlige og hjelpsomme. Foreldre bør også lære barna å ta ansvar, for eksempel å rydde etter seg og gjøre lekser. Det er også viktig å lære dem å være høflige og takke for hjelp.',
        },
        {
          id: 103,
          cat: 'society',
          examType: 'B',
          q: 'Hva kan barn hjelpe til med hjemme? Fra hvilken alder?',
          a: 'Barn kan hjelpe til hjemme fra de er små. Små barn kan rydde lekene sine og hjelpe til med å dekke bordet. Litt større barn kan vaske opp, kaste søppel og rydde rommet sitt. Når de blir eldre, kan de også lage enkel mat og vaske klær. Det er viktig at barn lærer å hjelpe til hjemme.',
        },
        {
          id: 104,
          cat: 'society',
          examType: 'C',
          q: 'Hva kan voksne lære av barn?',
          a: 'Voksne kan lære mye av barn. Barn er nysgjerrige og stiller mange spørsmål. De ser verden på en enkel og ærlig måte. Voksne kan også lære å være mer tålmodige og leke mer. Barn viser oss hvordan vi kan glede oss over små ting i hverdagen.',
        },
        {
          id: 105,
          cat: 'society',
          examType: 'C',
          q: 'Hvorfor er trening viktig for helsen?',
          a: 'Trening er viktig for helsen fordi det gir oss mer energi og gjør kroppen sterkere. Hvis man trener regelmessig, blir man sunnere og føler seg bedre. Trening hjelper også mot stress og gjør at man sover bedre. Man trenger ikke å trene hardt, men det er bra å gå tur, sykle eller gjøre enkle øvelser hver dag.',
        },
        {
          id: 106,
          cat: 'friends',
          examType: 'A',
          q: 'Hva kan du gjøre for å få nye venner?',
          a: 'For å få nye venner må man snakke med folk. Jeg prøver å være hyggelig og åpen. Jeg går på språkkafé og møter nye mennesker der. Det er også lurt å bli med på aktiviteter, for eksempel turgrupper eller trening. Hvis man snakker med kolleger eller naboer, kan man også få nye venner. Det viktigste er å være vennlig og ikke være redd for å starte en samtale.',
        },
        {
          id: 107,
          cat: 'friends',
          examType: 'C',
          q: 'Er det vanskelig å bli kjent med nye mennesker i Norge?',
          a: 'Ja, det er litt vanskelig å få nye venner i Norge. Mange nordmenn er hyggelige, men de er også litt reserverte. De liker best å snakke med folk de kjenner fra før. Det er lettere å bli kjent hvis man har noe felles. For eksempel hvis man jobber sammen eller trener sammen. Det er også lettere å få venner fra skolen, jobb eller fra apper på internett. Man må kunne norsk. Hvis man ikke snakker godt norsk, blir det vanskeligere.',
        },
        {
          id: 108,
          cat: 'friends',
          examType: 'A',
          q: 'Hvem liker du å snakke med? Hva snakker dere om? Hvor møtes dere?',
          a: 'Jeg liker å snakke med vennene mine og familien min. Vi snakker om mange ting. For eksempel hvordan dagen har vært, nyheter eller planer for helgen. Vi møtes ofte hjemme hos meg eller hos dem. Noen ganger møtes vi på kafé eller går en tur sammen.',
        },
        {
          id: 109,
          cat: 'friends',
          examType: 'A',
          q: 'Hva liker du å gjøre i fritiden? Hvem liker du å være sammen med?',
          a: 'I fritiden liker jeg å gå tur og slappe av. Noen ganger ser jeg på YouTube eller andre sosiale medier. Jeg liker også å være sammen med venner. Vi drikker kaffe og snakker sammen. Det er hyggelig. Noen ganger er jeg med familien min. Da lager vi mat eller ser på TV .',
        },
        {
          id: 110,
          cat: 'friends',
          examType: 'B',
          q: 'Kan dere snakke om hva dere spiser til middag?',
          a: 'Til middag spiser vi ofte vanlig norsk mat. For eksempel kjøttkaker, fisk eller pasta. Noen ganger lager vi mat fra hjemlandet mitt. Jeg liker å lage mat med mye smak. På hverdager lager vi enkel mat fordi vi har lite tid. I helgene har vi mer tid, så da lager vi noe ekstra godt.',
        },
        {
          id: 111,
          cat: 'friends',
          examType: 'A',
          q: 'Kan du fortelle om en person som er viktig for deg?',
          a: 'En person som er viktig for meg er moren min. Hun har alltid støttet meg og hjulpet meg. Hun er snill og omsorgsfull. Hvis jeg har problemer, kan jeg alltid snakke med henne. Hun gir meg gode råd og bryr seg om meg. Jeg er veldig takknemlig for henne.',
        },
        {
          id: 112,
          cat: 'friends',
          examType: 'A',
          q: 'Kan du fortelle om en jobb du ikke vil ha?',
          a: 'Jeg vil ikke jobbe som fisker. Det er en viktig jobb, men det er hardt arbeid. Man må jobbe lange dager, ofte ute i kaldt vær. Jeg liker bedre en jobb der jeg kan være inne og jobbe med mennesker. Men jeg respekterer de som jobber med det, fordi det er viktig for samfunnet.',
        },
        {
          id: 113,
          cat: 'friends',
          examType: 'A',
          q: 'Kan du fortelle om et yrke du er interessert i?',
          a: 'Jeg er interessert i å jobbe på restaurant. Jeg liker å lage mat og jobbe med mennesker. Det er fint å se at folk blir glade når de får god mat. Jeg liker også at det er et aktivt arbeid. Kanskje jeg kan jobbe som kokk eller servitør i framtiden.',
        },
        {
          id: 114,
          cat: 'situations',
          examType: 'B',
          q: 'Hva ville du gjort hvis du fant en lommebok på gaten?',
          a: 'Hvis jeg fant en lommebok på gaten, ville jeg prøvd å finne eieren. Jeg ville sett om det var et navn eller et telefonnummer inni. Hvis ikke, ville jeg levert den til politiet. Jeg synes det er viktig å være ærlig og gjøre det rette. Hvis jeg mistet lommeboken min, ville jeg også håpet at noen leverte den tilbake til meg.',
        },
        {
          id: 115,
          cat: 'situations',
          examType: 'B',
          q: 'Hva ville du gjort hvis du så noen stjele i en butikk?',
          a: 'Hvis jeg så noen stjele i en butikk, ville jeg sagt fra til en ansatt. Jeg tror det er viktig å gjøre noe, men jeg ville ikke konfrontert personen selv. Det er butikkens ansvar å håndtere slike situasjoner. Kanskje personen har en grunn til å stjele, men det er fortsatt feil. Jeg ville gjort det jeg kunne for å hjelpe uten å sette meg selv i fare. Jeg vet ikke helt. Det er ikke min sak, så jeg tror ikke jeg ville gjort noe. Jeg vil ikke blande meg inn i andres problemer. Butikken har kameraer og ansatte som passer på. Jeg ville bare fortsatt å handle som vanlig og ikke brydd meg.',
        },
        {
          id: 116,
          cat: 'situations',
          examType: 'B',
          q: 'Hva ville du gjort hvis du var sen til jobb?',
          a: 'Hvis jeg fant en lommebok på gaten, ville jeg prøvd å finne eieren. Jeg ville sett om det var et navn eller et telefonnummer inni. Hvis ikke, ville jeg levert den til politiet. Jeg synes det er viktig å være ærlig og gjøre det rette. Hvis jeg mistet lommeboken min, ville jeg også håpet at noen leverte den tilbake til meg.',
        },
        {
          id: 117,
          cat: 'situations',
          examType: 'B',
          q: 'Hva gjør du hvis du er syk og ikke kan dra på jobb?',
          a: 'Når jeg er syk prøver jeg å ta det med ro og hvile. Jeg drikker mye vann og spiser sunn mat. Hvis jeg har feber eller smerter tar jeg smertestillende. Hvis jeg ikke blir bedre etter noen dager kontakter jeg legen. Jeg prøver å unngå å smitte andre.',
        },
        {
          id: 118,
          cat: 'situations',
          examType: 'B',
          q: 'Hva gjør du hvis naboen lager for mye bråk om natten?',
          a: 'Jeg prøver å øve på norsk hver dag. Jeg ser på norske filmer og hører på podkaster for å bli vant til språket. Jeg snakker også med venner og kollegaer på norsk, selv om det noen ganger er vanskelig. Noen ganger leser jeg bøker eller aviser for å lære nye ord. Jeg tror det viktigste er å bruke språket så mye som mulig.',
        },
        {
          id: 119,
          cat: 'situations',
          examType: 'B',
          q: 'Hva gjør du hvis butikken har gitt deg for lite vekslepenger?',
          a: 'I pausene slapper jeg av. Jeg spiser mat og drikker kaffe eller te. Noen ganger snakker jeg med venner og klassekamerater. Hvis det er fint vær, går vi en liten tur ute. Noen ganger bruker jeg mobilen til å sjekke nyheter eller sende meldinger. Pausen er bra for å hvile før vi fortsetter undervisningen.',
        },
        {
          id: 120,
          cat: 'situations',
          examType: 'B',
          q: 'Hva gjør du hvis du ikke forstår noe på norsk?',
          a: 'I pausene slapper jeg av. Jeg spiser mat og drikker kaffe eller te. Noen ganger snakker jeg med venner og klassekamerater. Hvis det er fint vær, går vi en liten tur ute. Noen ganger bruker jeg mobilen til å sjekke nyheter eller sende meldinger. Pausen er bra for å hvile før vi fortsetter undervisningen.',
        },
        {
          id: 121,
          cat: 'situations',
          examType: 'A',
          q: 'Hva vil du gjøre når du er ferdig med norskprøven?',
          a: 'Når jeg er ferdig med norskprøven, vil jeg slappe av. Jeg har jobbet mye med norsk, så det blir fint med en pause. Men etter det vil jeg fortsette å lære mer norsk. Hvis jeg ikke kan fortsette å studere, vil jeg søke jobb. Jeg håper at norskprøven går bra, så jeg kan få flere muligheter.',
        },
        {
          id: 122,
          cat: 'situations',
          examType: 'A',
          q: 'Hva vil du gjøre når du blir gammel? Hvor vil du bo?',
          a: 'Når jeg blir gammel, vil jeg bo et sted som er rolig og fint. Kanskje i en liten leilighet eller et lite hus. Jeg vil være nær familien min hvis det er mulig, så vi kan besøke hverandre. Jeg vil gjerne gå turer og kanskje gjøre litt hobbyer som å lese eller strikke. Det viktigste er at jeg har det bra og ikke er alene.',
        },
        {
          id: 123,
          cat: 'situations',
          examType: 'A',
          q: 'Hvilke planer har du for framtida?',
          a: 'Jeg har mange planer for framtida. Først vil jeg bli bedre i norsk. Det er viktig for meg. Etter det vil jeg finne en fast jobb. Hvis det er mulig, vil jeg også studere. Jeg håper å få et godt liv i Norge sammen med familien og kanskje kjøpe mitt eget hus en dag.',
        },
        {
          id: 124,
          cat: 'situations',
          examType: 'A',
          q: 'Når snakker du norsk? Hvem snakker du norsk med?',
          a: 'Jeg snakker norsk hver dag. Jeg snakker norsk på skolen og når jeg handler i butikken. Jeg prøver også å snakke norsk med venner og lærere. Noen ganger snakker jeg norsk med naboer eller folk jeg møter. Jeg vil snakke mer norsk for å bli bedre.',
        },
        {
          id: 125,
          cat: 'situations',
          examType: 'A',
          q: 'Hvilke språk kan du snakke? Og når bruker du disse språkene?',
          a: 'Jeg kan snakke engelsk og norsk. Hjemme snakker jeg mest engelsk med familien min. Når jeg er på skolen, i butikken eller snakker med nordmenn, bruker jeg norsk. Jeg prøver å bruke mer norsk hver dag, så jeg kan bli bedre.',
        },
        {
          id: 126,
          cat: 'situations',
          examType: 'A',
          q: 'Kan du fortelle om en fest eller begivenhet du har vært på?',
          a: 'Ja, jeg har vært på en bursdagsfest for en venn. Det var veldig hyggelig. Vi spiste god mat og kake. Det var musikk, og noen danset. Vi snakket og lo mye sammen. Jeg møtte også nye mennesker. Det var en fin kveld, og alle hadde det gøy.',
        },
        {
          id: 127,
          cat: 'situations',
          examType: 'A',
          q: 'Hvordan feirer man nyttår i hjemlandet ditt?',
          a: 'I mitt hjemland feirer vi nyttår med familie og venner. Vi spiser god mat og har en hyggelig kveld sammen. Når klokka blir tolv, ser vi på fyrverkeri og ønsker hverandre godt nytt år. Noen steder har vi også musikk og dans. Det er en fin dag med mye glede.',
        },
        {
          id: 128,
          cat: 'situations',
          examType: 'A',
          q: 'Hvordan feirer man bryllup i hjemlandet ditt?',
          a: 'I mitt hjemland feirer vi bryllup med familie og venner. Det er en stor fest med mye mat og musikk. Bruden har ofte en fin kjole, og brudgommen har dress. Vi spiser god mat, danser og feirer sammen. Noen ganger varer festen hele dagen og kvelden, kanskje flere dager.',
        },
        {
          id: 129,
          cat: 'situations',
          examType: 'A',
          q: 'Kan du fortelle om hvordan du bruker sosiale medier?',
          a: 'Jeg bruker sosiale medier hver dag. Jeg liker å holde kontakt med familie og venner på WhatsApp og Messenger. Jeg bruker også Facebook og Instagram for å se nyheter og bilder. Hver dag ser jeg på YouTube for å lære norsk eller se interessante videoer. Sosiale medier hjelper meg å holde meg oppdatert og lære nye ting.',
        },
      ];

